<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Object2114_date</name>
   <tag></tag>
   <elementGuidId>83b3423f-52c1-46ea-bd4e-de163d57a680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;single-spa-application:@dev-tagsamurai/ts-mfe-console-asset-audit&quot;]/div/div[3]/div[2]/div/div/div[2]/div/div[2]/div/div[5]/span/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
