<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Object2202_rlegal</name>
   <tag></tag>
   <elementGuidId>f19c7f82-489f-40c4-9df2-e1e5dd6d342c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[18]/div/div[2]/div[2]/div/ul/li/ul/li[3]/ul/li[2]/div/span/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
