<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Object2136_raudit</name>
   <tag></tag>
   <elementGuidId>a5ef0582-97c8-4170-8058-6d494c94b920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[18]/div/div[2]/div[2]/div/ul/li/ul/li[3]/ul/li[1]/div/span/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
