<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Object2163_date</name>
   <tag></tag>
   <elementGuidId>7b22e8a3-8159-4a47-97e2-84d254d99ead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;single-spa-application:@dev-tagsamurai/ts-mfe-console-asset-audit&quot;]/div/div[3]/div/div/div/div[2]/div[2]/div[2]/div/div[1]/div[4]/div/div[7]/span/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
