<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Object0014_upload foto</name>
   <tag></tag>
   <elementGuidId>8209d948-a2b8-42f9-af3f-bda5b896e77e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[10]/div/div[2]/div/div[6]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.input-trigger.d-flex.align-items-center.justify-content-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>405ff079-a2af-410a-acd7-65feed5cf167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-trigger d-flex align-items-center justify-content-center</value>
      <webElementGuid>41036eb1-49cc-4253-aa4b-5a64a6591342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;p-overflow-hidden&quot;]/div[@class=&quot;p-dialog-mask p-component-overlay p-component-overlay-enter&quot;]/div[@class=&quot;p-dialog p-component p-ripple-disabled&quot;]/div[@class=&quot;p-dialog-content&quot;]/div[@class=&quot;row col-12 d-flex&quot;]/div[@class=&quot;form-group col-6&quot;]/div[1]/div[@class=&quot;d-flex col-12&quot;]/div[@class=&quot;input-trigger d-flex align-items-center justify-content-center&quot;]</value>
      <webElementGuid>1f99021a-c16e-46ac-80b3-f17825aa742d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]/div/div[6]/div/div/div</value>
      <webElementGuid>b10c3104-6e98-4e3d-9c62-123daa1344f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
