<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Object1681_date</name>
   <tag></tag>
   <elementGuidId>7fd51cd6-e365-4061-838f-1e2383dd52e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;single-spa-application:@dev-tagsamurai/ts-mfe-console-asset-maintenances&quot;]/div/div[3]/div[2]/div/div/div[2]/div/div[3]/div/div[3]/span/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
