<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Object1886_date</name>
   <tag></tag>
   <elementGuidId>a911c933-02f1-450e-afff-84807abe7c65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;single-spa-application:@dev-tagsamurai/ts-mfe-console-asset-maintenances&quot;]/div/div[3]/div[2]/div/div/div[2]/div/div[3]/div/div[5]/span/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
