<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Object2035_regal</name>
   <tag></tag>
   <elementGuidId>ba8101c3-52de-4c33-91fb-30952b5ad895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[7]/div/div[2]/div[2]/div/ul/li/ul/li[3]/ul/li[2]/div/span/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
